### ISSUE TITLE
fcli ssc attribute-definition list -> case sensitive?  // MAC

### ISSUE THREAD

**Issue by xakrurychle** [fortify/fcli#185]
qaprague@Jacks-Mac-mini ~ % fcli ssc attribute-definition list  --session krystof_session -q category=BUSINESS
 Id  Category  Guid                   Name                          Type      Required
 1   BUSINESS  BusinessRisk           Business Risk                 SINGLE    false
 2   BUSINESS  Compliance             Known Compliance Obligations  MULTIPLE  false
 3   BUSINESS  InfoClassification     Data Classification           MULTIPLE  false
 4   BUSINESS  ProjectClassification  Application Classification    MULTIPLE  false

if 'business' keyword is written in lower case I receive this error. Is the tool case sensitive or insensitive?

qaprague@Jacks-Mac-mini ~ % fcli ssc attribute-definition list  --session krystof_session -q category=business
No data

com.fortify.cli.common.rest.runner.UnexpectedHttpResponseException:
Request: GET https://qa-st-c7-kho01.prgqa.hpecorp.net:8443/ssc/api/v1/attributeDefinitions?limit=-1&orderby=category,name&q=category%3A%22business%22:
Response: 500
Response Body:
{"message":"An unexpected error occurred.","responseCode":500,"errorCode":-10103}
	at com.fortify.cli.common.rest.runner.config.UnirestUnexpectedHttpResponseConfigurer$UnexpectedHttpResponseInterceptor.onResponse(UnirestUnexpectedHttpResponseConfigurer.java:48)
	at kong.unirest.CompoundInterceptor.lambda$onResponse$1(CompoundInterceptor.java:48)
	at java.util.ArrayList.forEach(ArrayList.java:1541)
	at kong.unirest.CompoundInterceptor.onResponse(CompoundInterceptor.java:48)
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:134)
	at kong.unirest.Client.request(Client.java:57)
	at kong.unirest.BaseRequest.request(BaseRequest.java:359)
	at kong.unirest.BaseRequest.asObject(BaseRequest.java:260)
	at com.fortify.cli.common.rest.paging.PagingHelper.lambda$pagedRequest$0(PagingHelper.java:11)
	at kong.unirest.BaseRequest.asPaged(BaseRequest.java:351)
	at com.fortify.cli.common.rest.paging.PagingHelper.pagedRequest(PagingHelper.java:11)
	at com.fortify.cli.common.output.writer.output.standard.StandardOutputWriter.writeRecords(StandardOutputWriter.java:130)
	at com.fortify.cli.common.output.writer.output.standard.StandardOutputWriter.write(StandardOutputWriter.java:94)
	at com.fortify.cli.common.output.cli.mixin.spi.unirest.AbstractUnirestOutputHelper.write(AbstractUnirestOutputHelper.java:69)
	at com.fortify.cli.common.output.cli.cmd.unirest.AbstractUnirestOutputCommand.run(AbstractUnirestOutputCommand.java:50)
	at com.fortify.cli.common.rest.cli.mixin.AbstractUnirestRunnerMixin.run(AbstractUnirestRunnerMixin.java:27)
	at com.fortify.cli.common.rest.cli.mixin.AbstractSimpleUnirestRunnerMixin.run(AbstractSimpleUnirestRunnerMixin.java:14)
	at com.fortify.cli.common.rest.cli.cmd.AbstractUnirestRunnerCommand.run(AbstractUnirestRunnerCommand.java:41)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.fortify.cli.app.FortifyCLI.execute(FortifyCLI.java:81)
	at com.fortify.cli.app.FortifyCLI.main(FortifyCLI.java:61)

**Comment by rsenden** [comment]
Where possible, fcli uses server-side filtering to optimize performance. In this example, fcli passes the `q=category:"business"` request parameter to SSC, and SSC fails because this is not a valid category (SSC only recognizes uppercase `BUSINESS`). There's not much that fcli can do about this, other than reverting to client-side filtering. Ideally, SSC should return a more descriptive error message in the response body, or just return an empty collection.

For client-side filtering, fcli uses case-insensitive matching. I guess it can be confusing for users that case-sensitive matching is used for some fields, while case-insensitive matching is done for other fields. We already have another issue discussing this; see #125. Please comment on that issue if you have any suggestions.

Not sure why fcli first outputs `No data` and only then throws an exception; this requires more research.
