### ISSUE TITLE
Integration testing : 0.20230405.093348-dev_main: fod scan setup-sast module throw NullPointerException

### ISSUE THREAD

**Issue by rohitbaryha1** [fortify/fcli#278]
when setting up SAST scan, throw error of NullPointerException when not passing _--frequency, or --entitlement-frequency parameter.

here is the log:
Running Command: ./fcli-beta.exe fod scan setup-sast --entitlement-id=393 --technology-stack='JAVA/J2EE' --language-level='11' --audit-preference=Automated --assessment-type=Static INT_T_App1:INT_T_App1_Release1
./fcli-beta.exe : java.lang.NullPointerException
At line:1 char:1
+ ./fcli-beta.exe fod scan setup-sast --entitlement-id=393 --technology ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (java.lang.NullPointerException:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
./fcli-beta.exe : java.lang.NullPointerException
At line:1 char:1
+ ./fcli-beta.exe fod scan setup-sast --entitlement-id=393 --technology ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : NotSpecified: (java.lang.NullPointerException:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

	at com.fortify.cli.fod.entity.scan_sast.cli.cmd.FoDSastScanSetupCommand.getJsonNode(FoDSastScanSetupCommand.java:153)
	at com.fortify.cli.fod.entity.scan_sast.cli.cmd.FoDSastScanSetupCommand.getJsonNode(FoDSastScanSetupCommand.java:153)
	at 
com.fortify.cli.fod.output.cli.AbstractFoDJsonNodeOutputCommand.getJsonNode(AbstractFoDJsonNodeOutputCommand.java:11)
	at com.fortify.cli.fod.output.cli.AbstractFoDJsonNodeOutputCommand.getJsonNode(AbstractFoDJsonNodeOutputCommand.java:11)
	at com.fortify.cli.common.output.cli.cmd.AbstractOutputCommand.run(AbstractOutputCommand.java:45)
	at com.fortify.cli.common.output.cli.cmd.AbstractOutputCommand.run(AbstractOutputCommand.java:45)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2104)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2104)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2539)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2539)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2531)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2531)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2493)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2493)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2351)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2351)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2495)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2495)
	at picocli.CommandLine.execute(CommandLine.java:2248)
	at picocli.CommandLine.execute(CommandLine.java:2248)
	at com.fortify.cli.app.FortifyCLI.execute(FortifyCLI.java:86)
	at com.fortify.cli.app.FortifyCLI.execute(FortifyCLI.java:86)
	at com.fortify.cli.app.FortifyCLI.main(FortifyCLI.java:68)
	at com.fortify.cli.app.FortifyCLI.main(FortifyCLI.java:68)

**Comment by rsenden** [comment]
As indicated in the exception, this is caused by `FoDSastScanSetupCommand` calling a method on a `null` object in line 153, more specifically by calling `entitlementFrequency.name()` if `entitlementFrequency` is null (i.e., not specified on the command line).

Instead of adding a null-check here, the code should be refactored to make it less error-prone based on the suggestions in #279:

* Provide default option values such that enum values like these can never be null, and/or have the request class handle null values instead of handling this in the command implementation
* Have the request object accept enum values instead of having command implementations passing String/int/... representations of these enum values to request objects
* Use proper builder-style setter methods without `set` prefix
* All other suggestions related to enum handling / Jackson serialization/deserialization

Please review all existing enums, request/response classes and command implementations to apply these principles.

**Comment by kadraman** [comment]
Implemented in above commit to develop branch.
