### ISSUE TITLE
FCLI: Intermittent 404 Error

### ISSUE THREAD

**Issue by amrita9519** [fortify/fcli#600]
### Current Behavior

**Issue** 
We are encountering intermittent 404 errors while making API calls in FCLI to poll for Fortify scan results. Here is a concise overview of our scan process. 

- Authenticate with Fortify using API keys. 
- Package and submit the code for a SAST scan. 
- Sleep for 60 seconds after uploading to Fortify 
- Poll the API every 60 seconds to check the scan status. 
- Retrieve and interpret the scan results once completed. 

The 404 error occurs randomly during the polling phase, despite the scan being successfully initiated. This issue appears to be intermittent. 

**API Call:** 

Here’s the API call being made: 

`GET https://api.ams.fortify.com/api/v3/scans/{scanId}/summary `

**Error:** 

The error returned is: 

Response: 404 Not Found 
Response Body: null 

**Full logs for reference** 

```
com.fortify.cli.common.rest.unirest.UnexpectedHttpResponseException:  
Request:  
GET https://api.ams.fortify.com/api/v3/scans/{scanId}//summary:  
Response: 404 Not Found 
Response Body: 
null 
at com.fortify.cli.common.rest.unirest.config.UnirestUnexpectedHttpResponseConfigurer$UnexpectedHttpResponseInterceptor.onResponse(UnirestUnexpectedHttpResponseConfigurer.java:36) 
at kong.unirest.CompoundInterceptor.lambda$onResponse$1(CompoundInterceptor.java:48) 
at java.base@17.0.9/java.util.ArrayList.forEach(ArrayList.java:1511) 
at kong.unirest.CompoundInterceptor.onResponse(CompoundInterceptor.java:48) 
at kong.unirest.apache.ApacheClient.request(ApacheClient.java:134) 
at kong.unirest.Client.request(Client.java:57) 
at kong.unirest.BaseRequest.request(BaseRequest.java:365) 
at kong.unirest.BaseRequest.asObject(BaseRequest.java:266) 
at com.fortify.cli.fod._common.scan.helper.FoDScanHelper.getScanDescriptor(FoDScanHelper.java:57) 
at com.fortify.cli.fod._common.scan.cli.mixin.FoDScanResolverMixin$AbstractFoDScanResolverMixin.getScanDescriptor(FoDScanResolverMixin.java:36) 
at com.fortify.cli.fod._common.scan.cli.mixin.FoDScanResolverMixin$AbstractFoDScanResolverMixin.getScanDescriptor(FoDScanResolverMixin.java:40) 
at com.fortify.cli.fod._common.scan.cli.cmd.AbstractFoDScanGetCommand.getJsonNode(AbstractFoDScanGetCommand.java:31) 
at com.fortify.cli.fod._common.output.cli.AbstractFoDJsonNodeOutputCommand.getJsonNode(AbstractFoDJsonNodeOutputCommand.java:23) 
at com.fortify.cli.common.output.cli.cmd.AbstractOutputCommand.run(AbstractOutputCommand.java:33) 
at picocli.CommandLine.executeUserObject(CommandLine.java:2103) 
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2538) 
at picocli.CommandLine$RunLast.handle(CommandLine.java:2530) 
at picocli.CommandLine$RunLast.handle(CommandLine.java:2492) 
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2350) 
at picocli.CommandLine$RunLast.execute(CommandLine.java:2494) 
at picocli.CommandLine.execute(CommandLine.java:2247) 
at com.fortify.cli.app.runner.DefaultFortifyCLIRunner.run(DefaultFortifyCLIRunner.java:49) 
at com.fortify.cli.app.FortifyCLI.execute(FortifyCLI.java:38) 
at com.fortify.cli.app.FortifyCLI.main(FortifyCLI.java:32) 
```

### Environment

```markdown
OS: Ubuntu 22.04
fcli: 2.2.0
```

**Comment by rsenden** [comment]
Hi, this is a known FoD issue; it takes some time for building the scan summary after submitting a scan request, and the `summary` endpoint will return 404 errors until the scan summary is available. Sometimes it can take several minutes for the scan summary to be available.

It looks like you are manually polling the `summary` endpoint through the `fcli fod sast-scan get` commands; it would be better to use the `fcli fod sast-scan wait-for` command instead, as this uses a different (undocumented) `polling-summary` endpoint for retrieving current scan status.

General flow would be as follows:

```bash
fcli fod sast-scan start ... --store myscan
fcli fod sast-scan wait-for ::myscan::
```

Note that it is recommended to use fcli variables to pass the scan id to the `wait-for` command as illustrated above, as this will automatically pass `<release id>:<scan id>` to the `wait-for` command. Both id's are necessary to invoke the `polling-summary` endpoint. If you only pass `<scan id>` to the `wait-for` command, it will fall back to using the regular `summary` endpoint, potentially suffering from the same issue as you're currently experiencing.

Also note that you'll need at least fcli version 2.4.0 to utilize the `polling-summary` endpoint. Older fcli versions used the regular `summary` endpoint, thereby exhibiting the same behavior as what you're seeing.

**Comment by MikeTheSnowman** [comment]
Hey @amrita9519 , did rsenden's recommendation with the `wait-for` command help to address your issue?

**Comment by MikeTheSnowman** [comment]
Hey @amrita9519 . I just wanted to check in one more time the see if rsenden's recommendation addressed your issue. Seeing that there hasn't been a response from you since you raised this issue (it's been over a month now), I will now close this issue as resolved. Of course, you'll still be free to come back here after the fact to leave a follow up response.
