### ISSUE TITLE
Stream out of synk

### ISSUE THREAD

**Issue by LordBongio** [fortify/fcli#623]
### Current Behavior

when trying to upload a cyclondx file to the tenant, sometimes it "bugs out" and gives error "stream out of synk".
![2024-10-18 09_55_55-run-fortify-sast-sca-on-merge-job (#685192) · Jobs · Simpl _ Simpl-Open _ Develo](https://github.com/user-attachments/assets/eb6c6490-1a73-43eb-b43e-62b016b6e32a)

**Comment by LordBongio** [comment]
there is no real reason. 90% of the time it works and sometimes it doesn't. pipeline command is always the same

**Comment by MikeTheSnowman** [comment]
Hey @LordBongio. Sorry if this is a silly recommendation, but how do you feel about updating your script to simply retry uploading your first attempt at uploading fails? Or better yet, setup your code with a retry-limit. 

Unfortunately, we have our hands tied with other important tasks and are not able to investigate the underline reason as to why the upload fails.

I do have one question for you though. Is there any special reason as to why you're referencing your release using the release-id? If you know the name of the application  and the name of the release, you can simply do something like `--release "<AppName>:<ReleaseName>"`. Would it be correct to assume that this is already contained in `$FORTIFY_RELEASE`?

**Comment by LordBongio** [comment]
hi,
yes we tryed several times relaunching the failed step and it doesn't work.
I honestly don't remember why we are using the release id instead of the other convention but that same release id is later on used by sast and sca and it works, so it is not the issue.
we will wait to find out why.
Thanks

**Comment by rsenden** [comment]
Hi @LordBongio, we've seen similar issues with OSS imports before. As a temporary work-around, can you please try uploading the file in one chunk, i.e., by setting the `--chunk-size` option to a value that's larger than the file that you're trying to import? I'm not sure whether there's any maximum chunk size, so this may not work if the file is too large. I'll raise this issue with the FoD product manager, you can also consider opening an FoD support case as this seems to be an issue on the FoD side.

**Comment by LordBongio** [comment]
hi, i see no -chunk-size option in fod oss import

**Comment by rsenden** [comment]
Hi @LordBongio, which fcli version are you using? I think the `--chunk-size` option was added in fcli 2.5.0, latest version at the moment is 2.7.1.

**Comment by LordBongio** [comment]
> Hi @LordBongio, which fcli version are you using? I think the `--chunk-size` option was added in fcli 2.5.0, latest version at the moment is 2.7.1.

i'm now using the new version with the chunk file and it seems to work.
the only problem is that a lot of times i see that it accepts the import with status "IMPORT REQUESTED" but i never see the actual results in the platform, it gets uploaded into the oblivion.
Have you ever had this issue?

**Comment by rsenden** [comment]
Hi @LordBongio, I haven't seen this issue before. It may be worth waiting for the FoD 24.4 release to see whether this issue is still present; if so, please consider opening an FoD support ticket stating that SBOMs uploaded through the `/api/v3/releases/{id}/open-source-scans/import-cyclonedx-sbom` endpoint often are not shown in the FoD UI despite this endpoint returning a successful response. In the meantime, I'll again raise this issue to the FoD team to see whether they can provide any further input on these issues.

**Comment by rsenden** [comment]
Hi @LordBongio, just a quick side note; your first screenshot above shows a relatively complex command to set an `FOD_RELEASE` variable by piping the output of the `fcli fod rel get` command to `grep`, `cut` & `tr`. Looks like you're trying to retrieve the release id here, which could likely be simplified with a command like `fcli fod rel get ${FORTIFY_RELEASE} -o expr={releaseId}`

**Comment by kadraman** [comment]
This is repeatable. If the SBOM is larger than the default chunk size (1048576 bytes) it fails. This is why I added `--chunk-size` as a workaround - you can try setting this to the size of file while this is fixed. This should have been fixed in 24.4 but doesn't appear to have been.

**Comment by rsenden** [comment]
@kadraman Any idea whether this has been fixed by now? If not, we should discuss this issue with the FoD team.

**Comment by kadraman** [comment]
I have just tried this on "dev/v3.x" fcli and the problem still exists. I am using SBOM from [here](https://github.com/CycloneDX/bom-examples/blob/master/SBOM/keycloak-10.0.2/bom.json) and command:

```
 java -jar ./build/libs/fcli.jar fod oss import -f keyclock-10.0.2-sbom.json  --release "SBOM-Examples [KAL]:keycloak-10.0.2-from-fcli"
FcliSimpleException: Error uploading file
        at com.fortify.cli.fod._common.rest.helper.FoDFileTransferHelper.uploadChunked(FoDFileTransferHelper.java:101)
Caused by: com.fortify.cli.common.rest.unirest.UnexpectedHttpResponseException:   
  Request: PUT https://api.emea.fortify.com/api/v3/releases/164445/open-source-scans/import-cyclonedx-sbom?importScanSessionId=a929c33b-d120-43f0-a5f5-095da2e2e1e3&fileLength=2214757&fragNo=1&offset=1048576: 
  Reason: HTTP 400 Bad Request
  Body: 
    {"errors":[{"errorCode":null,"message":"Stream out of sync"}]}
  ----
        at com.fortify.cli.common.rest.unirest.config.UnirestUnexpectedHttpResponseConfigurer$UnexpectedHttpResponseInterceptor.onResponse(UnirestUnexpectedHttpResponseConfigurer.java:36)
        at kong.unirest.CompoundInterceptor.lambda$onResponse$1(CompoundInterceptor.java:48)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at kong.unirest.CompoundInterceptor.onResponse(CompoundInterceptor.java:48)
        at kong.unirest.apache.ApacheClient.request(ApacheClient.java:134)
        at kong.unirest.Client.request(Client.java:57)
        at kong.unirest.BaseRequest.request(BaseRequest.java:365)
        at kong.unirest.BaseRequest.asString(BaseRequest.java:218)
        at com.fortify.cli.fod._common.rest.helper.FoDFileTransferHelper.uploadChunked(FoDFileTransferHelper.java:94)
        at com.fortify.cli.fod._common.scan.cli.cmd.AbstractFoDScanImportCommand.getJsonNode(AbstractFoDScanImportCommand.java:61)
        at com.fortify.cli.fod._common.output.cli.cmd.AbstractFoDJsonNodeOutputCommand.getJsonNode(AbstractFoDJsonNodeOutputCommand.java:23)
        at com.fortify.cli.common.output.cli.cmd.AbstractOutputCommand.call(AbstractOutputCommand.java:34)
        at com.fortify.cli.common.output.cli.cmd.AbstractOutputCommand.call(AbstractOutputCommand.java:23)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2118)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2538)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2530)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2492)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2350)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2494)
        at picocli.CommandLine.execute(CommandLine.java:2247)
        at com.fortify.cli.app.runner.DefaultFortifyCLIRunner.run(DefaultFortifyCLIRunner.java:63)
        at com.fortify.cli.app.FortifyCLI.execute(FortifyCLI.java:38)
        at com.fortify.cli.app.FortifyCLI.main(FortifyCLI.java:32)
```

SBOM will need to be converted to v1.4 format using [cyclonedx-cli](https://github.com/CycloneDX/cyclonedx-cli).

Importing an SBOM (without running a Debricked scan - an option which is not available from API) also doesn't show the imported components. I will check if this the correct behaviour as it doesn't seem right to me.

**Comment by kadraman** [comment]
We are awaiting a server-side Hotfix for OpenText Application Secure Core 25.2 which will hopefully address this.
